export const SOURCES = [
  { id: "src-ncrf", title: "National Credit Framework (NCrF)", url: "https://www.abc.gov.in", publisher: "Ministry of Education / ABC", retrievedAt: "2026-10-03", notes: "F1. 1 credit = 30 notional learning hours; 1,200 hours/year = 40 credits.", tierHint: "V2" },
  { id: "src-nsqf", title: "NSQF and NCVET", url: "https://www.ncvet.gov.in", publisher: "NCVET", retrievedAt: "2026-10-03", notes: "F2. Launched Dec 2013. Levels revised in 2023. Verify trade mapping on NQR.", tierHint: "V2" },
  { id: "src-nqr", title: "National Qualifications Register", url: "https://nqr.gov.in", publisher: "NCVET", retrievedAt: "2026-10-03", notes: "F2. Qualifications listed on NQR.", tierHint: "V2" },
  { id: "src-pmsetu", title: "PM-SETU cabinet and launch notes", url: "https://www.pmindia.gov.in", publisher: "Prime Minister's Office", retrievedAt: "2026-10-03", notes: "F3. Cabinet 7 May 2025. ₹60,000 crore. Launched 4 Oct 2025. 1,000 ITIs.", tierHint: "V2" },
  { id: "src-loksabha-1542", title: "Lok Sabha Unstarred Q.1542", url: "https://sansad.in", publisher: "Lok Sabha", retrievedAt: "2026-10-03", notes: "F3. 9 Feb 2026. Target 20 lakh youth.", tierHint: "V2" },
  { id: "src-naps", title: "NAPS MSDE factsheet", url: "https://www.msde.gov.in", publisher: "MSDE", retrievedAt: "2026-10-03", notes: "F4. 25% of prescribed stipend up to ₹1,500/apprentice/month. NAPS-2.", tierHint: "V2" },
  { id: "src-sidh", title: "Skill India Digital Hub", url: "https://www.skillindiadigital.gov.in", publisher: "MSDE", retrievedAt: "2026-10-03", notes: "F5. Launched 13 Sep 2023.", tierHint: "V2" },
  { id: "src-dpdp", title: "Digital Personal Data Protection Act, 2023 and Rules", url: "https://www.meity.gov.in", publisher: "MeitY", retrievedAt: "2026-10-03", notes: "F6. Rules notified Nov 2025. Consent-manager from 14 Nov 2026. Child duties from 14 May 2027.", tierHint: "V2" },
  { id: "src-ajith", title: "Ajithkumar & Pilz (2019), Education + Training 61(2)", url: "https://doi.org/10.1108/ET-04-2018-0092", publisher: "Emerald", retrievedAt: "2026-10-03", notes: "F7. ITI image in Maharashtra and Haryana.", tierHint: "V2" },
  { id: "src-rs-1430", title: "Rajya Sabha Unstarred Q.1430", url: "https://sansad.in", publisher: "Rajya Sabha", retrievedAt: "2026-10-03", notes: "F7. 12 Feb 2021. Travel cost and gender perception.", tierHint: "V2" },
  { id: "src-plfs", title: "PLFS Annual Report 2025 (secondary citation)", url: "https://www.mospi.gov.in", publisher: "MoSPI", retrievedAt: "2026-10-03", notes: "F10. Pending steward check. Men ₹24,217; women ₹18,353 regular wage/salaried. Not for family UI.", tierHint: "V1" },
  { id: "src-demo", title: "Nourish synthetic baseline", url: "https://example.com/nourish-synthetic", publisher: "Nourish prototype", retrievedAt: "2026-10-03", notes: "V0 illustrative seed. Not a government statistic.", tierHint: "V0" },
] as const;

export const STATES = [
  { id: "st-up", name: "Uttar Pradesh", code: "UP" },
  { id: "st-mh", name: "Maharashtra", code: "MH" },
  { id: "st-tn", name: "Tamil Nadu", code: "TN" },
  { id: "st-br", name: "Bihar", code: "BR" },
  { id: "st-rj", name: "Rajasthan", code: "RJ" },
  { id: "st-ka", name: "Karnataka", code: "KA" },
] as const;

export const DISTRICTS: { id: string; name: string; stateId: string; rural: boolean; lat: number; lng: number }[] = [
  ["d-neemganj", "Neemganj", "st-up", false, 28.9, 77.7],
  ["d-suryapur", "Suryapur", "st-up", false, 26.8, 80.9],
  ["d-kalyanbagh", "Kalyanbagh", "st-up", true, 27.2, 79.5],
  ["d-loharpur", "Loharpur", "st-up", true, 25.4, 82.1],
  ["d-mangoan", "Mangoan", "st-mh", false, 19.1, 72.9],
  ["d-varadpur", "Varadpur", "st-mh", false, 18.5, 73.8],
  ["d-sahyadri", "Sahyadri Nagar", "st-mh", true, 17.7, 74.2],
  ["d-talewadi", "Talewadi", "st-mh", true, 20.1, 75.4],
  ["d-thenpadi", "Thenpadi", "st-tn", false, 13.1, 80.2],
  ["d-marudham", "Marudham", "st-tn", false, 11.0, 77.0],
  ["d-kaveryoor", "Kaveryoor", "st-tn", true, 10.8, 78.7],
  ["d-mullai", "Mullai", "st-tn", true, 9.9, 78.1],
  ["d-gangauli", "Gangauli", "st-br", false, 25.6, 85.1],
  ["d-sonpurwa", "Sonpurwa", "st-br", true, 25.7, 84.4],
  ["d-mithilapur", "Mithilapur", "st-br", true, 26.1, 85.9],
  ["d-baghpur", "Baghpur", "st-br", false, 25.2, 86.0],
  ["d-marugarh", "Marugarh", "st-rj", false, 26.9, 75.8],
  ["d-pushpnagar", "Pushpnagar", "st-rj", false, 26.5, 74.6],
  ["d-aravalli", "Aravalli Basti", "st-rj", true, 25.2, 73.1],
  ["d-registan", "Registan Gaon", "st-rj", true, 26.2, 73.0],
  ["d-malnad", "Malnadpet", "st-ka", false, 13.3, 75.8],
  ["d-kaveridock", "Kaveri Dock", "st-ka", false, 12.3, 76.6],
  ["d-bayalu", "Bayaluseeme", "st-ka", true, 15.4, 75.7],
  ["d-hasiru", "Hasiru Halli", "st-ka", true, 14.5, 75.9],
].map(([id, name, stateId, rural, lat, lng]) => ({
  id: id as string,
  name: name as string,
  stateId: stateId as string,
  rural: Boolean(rural),
  lat: lat as number,
  lng: lng as number,
}));

export const TRADES = [
  ["electrician", "Electrician", "electrical", "4", 24, "Class 10", 8000, 22000, "zap"],
  ["fitter", "Fitter", "manufacturing", "4", 24, "Class 10", 8000, 20000, "wrench"],
  ["welder", "Welder", "manufacturing", "3.5", 12, "Class 8", 6000, 18000, "flame"],
  ["mv-mechanic", "Motor Vehicle Mechanic", "automotive", "4", 24, "Class 10", 12000, 28000, "car"],
  ["plumber", "Plumber", "construction", "3.5", 12, "Class 8", 5000, 15000, "droplet"],
  ["rac", "Refrigeration and AC", "electrical", "4.5", 24, "Class 10", 15000, 35000, "snowflake"],
  ["solar", "Solar PV Installer", "green", "4", 6, "Class 10", 7000, 18000, "sun"],
  ["ev-tech", "EV Technician", "automotive", "4.5", 12, "Class 10", 18000, 40000, "battery"],
  ["cnc", "CNC Machinist", "manufacturing", "4.5", 24, "Class 10", 20000, 45000, "cog"],
  ["copa", "COPA", "it", "4", 12, "Class 12", 6000, 16000, "monitor"],
  ["sewing", "Sewing and Fashion", "apparel", "3.5", 12, "Class 8", 4000, 14000, "scissors"],
  ["beauty", "Beauty and Wellness", "services", "3", 6, "Class 8", 5000, 20000, "spark"],
  ["gda", "General Duty Assistant", "health", "4", 12, "Class 10", 8000, 22000, "heart"],
  ["mobile", "Mobile Repair", "electronics", "3.5", 6, "Class 8", 5000, 16000, "phone"],
  ["hospitality", "Hospitality", "services", "4", 12, "Class 10", 10000, 30000, "utensils"],
  ["retail", "Retail Associate", "services", "3", 6, "Class 8", 3000, 12000, "store"],
] as const;

export const SECTORS = [
  ["electrical", "Electrical"],
  ["manufacturing", "Manufacturing"],
  ["automotive", "Automotive"],
  ["construction", "Construction"],
  ["green", "Green energy"],
  ["it", "Information technology"],
  ["apparel", "Apparel"],
  ["services", "Services"],
  ["health", "Health"],
  ["electronics", "Electronics"],
] as const;

export const CARDS: { slug: string; title: string; body: string; topic: string; sourceId?: string }[] = [
  { slug: "ncrf-credit", title: "Skills can count toward a degree", body: "Under NCrF, 1 credit is 30 notional learning hours. About 1,200 hours in a year is 40 credits. Vocational and apprenticeship credits can be banked in the Academic Bank of Credits. Confirm the exact mapping with the institution.", topic: "ladder", sourceId: "src-ncrf" },
  { slug: "nsqf-meaning", title: "What NSQF means", body: "NSQF is the skill ladder. It started in December 2013 and is regulated by NCVET. Levels were revised in 2023, so a trade’s level must be read with the framework version and checked on the National Qualifications Register.", topic: "ladder", sourceId: "src-nsqf" },
  { slug: "pm-setu", title: "PM-SETU and ITI workshops", body: "The Union Cabinet approved PM-SETU on 7 May 2025 with a ₹60,000 crore outlay. It upgrades 1,000 government ITIs in a hub-and-spoke model and 5 NSTI centres. It was launched on 4 October 2025. This is a scheme fact, not a promise about one campus.", topic: "facilities", sourceId: "src-pmsetu" },
  { slug: "naps", title: "Earn while you learn", body: "Under NAPS, the government reimburses employers 25% of the prescribed apprentice stipend, up to ₹1,500 per apprentice per month. The course should be NSQF-aligned. A trainee’s own stipend is shown only when it is in the dataset.", topic: "funding", sourceId: "src-naps" },
  { slug: "sidh", title: "Skill India Digital Hub", body: "SIDH is digital public infrastructure launched by MSDE on 13 September 2023. Nourish is a family layer in front of it. Enrolment stays on SIDH or the provider.", topic: "ecosystem", sourceId: "src-sidh" },
  { slug: "verify-centre", title: "How to verify a training centre", body: "Ask for the affiliation letter, the trainer’s qualification, a current batch timetable, and a fee receipt format. Visit the workshop. Do not pay the full fee on the first day.", topic: "trust", sourceId: "src-nqr" },
  { slug: "fraud-flags", title: "Fraud red flags", body: "Walk away from guaranteed government jobs, cash-only fees, missing address, or pressure to decide today. Report the centre to a counsellor.", topic: "trust" },
  { slug: "women-image", title: "What research says about image", body: "Ajithkumar and Pilz (2019) found that the low-status image of ITIs was fading in Maharashtra and Haryana, but ITIs still lacked a strong image. This is a study finding, not a local placement rate.", topic: "gender", sourceId: "src-ajith" },
  { slug: "girls-barriers", title: "Travel and perception", body: "Rajya Sabha Unstarred Question 1430 (12 February 2021) cites travel cost and the perception that ITIs suit men as barriers to women’s participation. Ask about hostel and transport.", topic: "gender", sourceId: "src-rs-1430" },
  { slug: "safety-basics", title: "Workshop safety basics", body: "Look for goggles, gloves, shoes, a first-aid box, and a teacher present. Night travel to a centre is a separate family decision.", topic: "safety" },
  { slug: "certificate-value", title: "What a certificate is worth", body: "A certificate helps when the qualification is on the National Qualifications Register or issued by a recognised awarding body. Ask for the QP code or NQR id.", topic: "trust", sourceId: "src-nqr" },
  { slug: "not-a-promise", title: "No one can promise a job", body: "Placement rates describe a past cohort. They are not an offer to this learner. If someone promises 100% placement, treat that as a warning.", topic: "honesty" },
  { slug: "degree-bridge", title: "Degree and skill can meet", body: "Some learners should stay on a degree path. Others can start a trade and later use credits for a diploma or degree. The ladder shows both. It does not rank one as best.", topic: "ladder", sourceId: "src-ncrf" },
  { slug: "who-not-for", title: "Who a trade is not for", body: "Each trade lists health, study, or location limits. If those fit the learner, say so early. A mismatch is a useful finding.", topic: "honesty" },
  { slug: "family-roi", title: "A plain way to see fees", body: "When both fees and a median earning exist, we show an illustrative count of months to recover fees. It ignores living costs and is not financial advice.", topic: "funding" },
];

const EXTRA = [
  "Day starts with a toolbox check, not a lecture.",
  "Local employers hire by category: workshops, hospitals, hotels, or sites — we do not invent company names.",
  "Ask what ‘placed’ means: job, apprenticeship, or self-employment, and in how many months.",
  "A small cohort is hidden. We step up to district or state and say so.",
  "Women’s placement is shown when the dataset has it and the learner is a girl.",
  "Hostel and bus routes matter as much as the syllabus.",
  "Class 8, 10, or 12 is an entry rule from the trade, not a judgement.",
  "Marks bands are optional. They never block a conversation.",
  "Income bands stay on the device unless the family consents to analytics.",
  "A parent can speak first. The learner can disagree without being shamed.",
  "Voice works when reading does not. Captions stay on screen.",
  "Assisted Mode is for a help desk. The screen can clear after five quiet minutes.",
  "Two phones can join one room with a six-digit code.",
  "Demo numbers always wear a demo-data ribbon.",
  "Pending figures stay in the steward queue, not in the family chat.",
  "PM-SETU is about facilities and status, not a personal seat.",
  "NAPS money goes to the employer reimbursement rules, not as a cash promise to the family.",
  "Compare a trade with a degree path using words when numbers do not exist.",
  "Social perception is a real objection. Answer it with respect and evidence, not slogans.",
  "Migration for work should be costed: rent, safety, and who remains at home.",
  "Marriage timing is the family’s to decide. Training does not have to be framed as a delay or a rush.",
  "Automation changes tools. Ask which tasks in this trade are hands-on.",
  "Physical work can be skilled. The ladder shows technician and supervisor steps.",
  "Language support is part of access. Bring a family interpreter if you wish.",
  "Elder veto is a signal to slow down, not to bypass the elder.",
  "If the learner is unsure, shortlist two trades, not ten.",
  "Government jobs need their own exam path. A trade does not replace that exam.",
  "Lost academic year: check credit transfer before assuming the year is wasted.",
  "Fee ranges are min–max from the seed, labelled illustrative.",
  "Questions to ask before you pay are on every provider page.",
  "Report a wrong number. It goes to the AI quality queue.",
  "Counsellors see a case only if the family allowed sharing.",
  "Admins never see the transcript.",
  "Delete my data removes the family room, not the synthetic dashboard.",
  "Retention default is 90 days for transcripts.",
  "Cells smaller than 10 people are hidden on the admin grid.",
  "Hotspots need at least 30 sessions in 30 days and a high resistance score.",
  "An intervention is a logged action, then a before/after look. It is not proof of cause.",
  "English, Hindi, Marathi, and Tamil are first-class. Other languages would be marked auto-translated.",
  "Helplines are listed with a date. Re-check them before a demo.",
  "CHILDLINE 1098 and Tele-MANAS 14416 appear when a conversation is sensitive.",
  "This prototype is not an official government portal.",
  "Open the plan in WhatsApp as an image. The print view is the PDF path.",
  "Offline, the last plan and district cards can still open.",
  "Judge Mode shows the trace: tags, fact ids, and whether the scripted guide replied.",
];

EXTRA.forEach((body, i) => {
  CARDS.push({
    slug: `guide-${i + 1}`,
    title: body.split(".")[0] ?? `Guide ${i + 1}`,
    body,
    topic: "guide",
  });
});
